version: 0.2

env:
  variables:
    AWSCOPY: "aws s3 cp s3://docker-ecs-simple/simplewebappdev.war simplewebapp.war"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo docker build    
      - docker build -t simplewebapp .
  post_build:
    commands:
      - echo docker push
