version: 0.2

env:
  variables:
    AWSCOPY: "aws s3 cp s3://docker-ecs-simple/simplewebappdev.war simplewebapp.war"

phases:
  pre_build:
    commands:
      # Verify AWS CLI Version
      - echo "Verify AWS CLI Version..."
      - aws --version
      # Login to ECR Registry for docker to push the image to ECR Repository
      - echo "Login in to Amazon ECR..."
      - eval $(aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 116345098631.dkr.ecr.ap-southeast-1.amazonaws.com)
  build:
    commands:
      - echo docker build    
      - docker build -t 116345098631.dkr.ecr.ap-southeast-1.amazonaws.com/simplewebapp:latest .
  post_build:
    commands:
      - echo docker push
      - docker push 116345098631.dkr.ecr.ap-southeast-1.amazonaws.com/simplewebapp:latest
