apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-simplewebapp-deployment
  labels:
    app: simplewebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simplewebapp
  template:
    metadata:
      labels:
        app: simplewebapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: simplewebapp
        image: 116345098631.dkr.ecr.ap-southeast-1.amazonaws.com/simplewebapp:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
      nodeSelector:
        kubernetes.io/os: linux
