apiVersion: v1
kind: Service
metadata:
  name: eks-simplewebapp-service
  labels:
    app: eks-simplewebapp
spec:
  selector:
    app: eks-simplewebapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
